### ISSUE TITLE
Resin.exe not grabbing UID

### ISSUE THREAD

**Issue by Dragoonstorm1** [Beastwick18/genshin-real-time-notes#1]
ZZZ's Charge.exe works perfectly!
Genshin's Resin.exe lets me login but doesn't grab the cookie, or token, or something. But anyway hits me with the error message <Could not find valid UID: Got ''''> (I don't know if they're apostrophes, but doesnt seem like asterisks)

Anyway, log says simply 2 lines:
2024/10/15 13:06:58 [INFO] Application start
2024/10/15 13:06:58 [FAIL] Unable to read config .\genshin_cookie.json

There is no such genshin_cookie.json
But like i said, ZZZ's zzz_cookie.json works perfectly. If Charge.exe created the cookie.json with token field i could've at least manually input the UID...

**Comment by Beastwick18** [comment]
Looks like the formatting of the webpage changed a bit, so the LoginForm wasn't able able to grab the UID. HSR seems to be unchanged for now.

8956f4f should fix this. To prevent this from being as much of an issue in the future, I'll try to add a manual fill-in-the-blank popup for missing info.

New release should be out soon with this fix, and another will be out once new popup is done.

**Comment by Beastwick18** [comment]
Fixed in [v0.0.6](https://github.com/Beastwick18/genshin-real-time-notes/releases/tag/v0.0.6)

**Comment by Dragoonstorm1** [comment]
Thanks <3
And here we have another problem: windows defender is flagging the latest versions as Trojan now....

**Comment by Beastwick18** [comment]
Yeah, I've had that happen before with this program. It's most likely because it has another exe bundled inside of it (the login form, which was made using Visual Studio). This was done to make it easier to use, since you just run the `resin.exe`, and the login form automatically extracts itself. I would've made it in Go instead of visual studio, but I just couldn't get WebView working.

The source code for both the Login Form are both visible on this repo in case you're worried and want to check.

To prevent this from being a problem, I'll likely have to use an actual installer maker, or look into signing the exe.

If you do trust the source code, there should be a way to add this file as an exception to prevent it being flagged in the future.
